# Generated by Django 4.2.13 on 2026-04-20 17:50

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True)),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('typical_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('phones', 'Phones'), ('electronics', 'Electronics'), ('clothing', 'Clothing'), ('furniture', 'Furniture'), ('vehicles', 'Vehicles'), ('other', 'Other')], max_length=50)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('old', 'Old')], max_length=10)),
                ('user_estimated_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('system_estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('want_text', models.TextField(help_text='What do you want in exchange?')),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('traded', 'Traded')], default='active', max_length=20)),
                ('image_url', models.URLField(blank=True, help_text='Optional link to an image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='core.barteruser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_item_description', models.TextField(blank=True, help_text='Describe what you are offering in return')),
                ('cash_topup', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('suggested_cash_topup_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('suggested_cash_topup_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('contact_revealed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_made', to='core.barteruser')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.listing')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_received', to='core.barteruser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
