# Generated by Django 6.0.5 on 2026-05-13 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sitesettings_notification_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('university_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['university_name'],
            },
        ),
        migrations.CreateModel(
            name='CampusMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TradeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UniversityDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='e.g. ug.edu.gh', max_length=100, unique=True)),
                ('university_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'University Email Domain',
                'verbose_name_plural': 'University Email Domains',
                'ordering': ['university_name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='savedlisting',
            name='unique_user_saved_listing',
        ),
        migrations.RenameIndex(
            model_name='pricesample',
            new_name='core_prices_categor_11446e_idx',
            old_name='core_pricesampl_cat_scraped_idx',
        ),
        migrations.RemoveField(
            model_name='barteruser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='location',
        ),
        migrations.AddField(
            model_name='barteruser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='barteruser',
            name='contact_reveal_preference',
            field=models.CharField(choices=[('on_any_offer', 'Reveal to anyone who sends an offer'), ('on_accepted_offer', 'Reveal only after I accept an offer')], default='on_accepted_offer', max_length=20),
        ),
        migrations.AddField(
            model_name='barteruser',
            name='is_student_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='barteruser',
            name='location_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='barteruser',
            name='location_neighbourhood',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='barteruser',
            name='location_region',
            field=models.CharField(blank=True, choices=[('greater_accra', 'Greater Accra'), ('ashanti', 'Ashanti'), ('western', 'Western'), ('eastern', 'Eastern'), ('central', 'Central'), ('northern', 'Northern'), ('upper_east', 'Upper East'), ('upper_west', 'Upper West'), ('volta', 'Volta'), ('oti', 'Oti'), ('bono', 'Bono'), ('bono_east', 'Bono East'), ('ahafo', 'Ahafo'), ('western_north', 'Western North'), ('north_east', 'North East'), ('savannah', 'Savannah')], max_length=50),
        ),
        migrations.AddField(
            model_name='barteruser',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Link to your portfolio, Instagram, or website.'),
        ),
        migrations.AddField(
            model_name='barteruser',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='barteruser',
            name='student_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barteruser',
            name='website_url',
            field=models.URLField(blank=True, help_text='Optional additional URL.'),
        ),
        migrations.AddField(
            model_name='listing',
            name='ai_enrichment',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='ai_enrichment_admin_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='ai_enrichment_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='ai_enrichment_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='availability_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='cash_topup_direction',
            field=models.CharField(choices=[('willing_to_pay', 'Willing to pay a top-up'), ('willing_to_receive', 'Willing to receive a top-up'), ('neither', 'No cash top-up')], default='neither', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='collection_method',
            field=models.CharField(choices=[('pickup_only', 'Pickup Only'), ('delivery_available', 'Delivery Available'), ('can_ship', 'Can Ship')], default='pickup_only', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='colour',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='deposit_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='deposit_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, choices=[(7, '7 days'), (14, '14 days'), (30, '30 days'), (60, '60 days')], help_text='Required for temporary listings.', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex'), ('kids', 'Kids')], max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_behaviour',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary')], default='permanent', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('physical', 'Physical Item'), ('handmade', 'Handmade Item'), ('service', 'Service / Commission')], default='physical', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='location_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='location_neighbourhood',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='location_region',
            field=models.CharField(blank=True, choices=[('greater_accra', 'Greater Accra'), ('ashanti', 'Ashanti'), ('western', 'Western'), ('eastern', 'Eastern'), ('central', 'Central'), ('northern', 'Northern'), ('upper_east', 'Upper East'), ('upper_west', 'Upper West'), ('volta', 'Volta'), ('oti', 'Oti'), ('bono', 'Bono'), ('bono_east', 'Bono East'), ('ahafo', 'Ahafo'), ('western_north', 'Western North'), ('north_east', 'North East'), ('savannah', 'Savannah')], max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='materials_used',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='model_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='rental_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='rental_payment_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='rental_period_unit',
            field=models.CharField(blank=True, choices=[('hourly', 'Per Hour'), ('daily', 'Per Day'), ('weekly', 'Per Week'), ('per_event', 'Per Event')], max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='repair_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='service_scope',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='service_timeline_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='transaction_type',
            field=models.CharField(choices=[('trade', 'Trade'), ('rental', 'Rental')], default='trade', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='warranty_duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='warranty_offered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='match_tier',
            field=models.CharField(blank=True, choices=[('exact', 'Exact'), ('strong', 'Strong'), ('potential', 'Potential')], max_length=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='counter_cash_topup',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cash top-up amount the seller is requesting as a counteroffer.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='counter_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('trade', 'Trade Offer'), ('rental', 'Rental Offer')], default='trade', max_length=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='pending_timeout_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='rental_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='rental_payment_offered',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='rental_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='listing_stale_days',
            field=models.PositiveIntegerField(default=60, help_text='Days before an active permanent listing with no matches is prompted for review.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='offer_timeout_days',
            field=models.PositiveIntegerField(default=3, help_text='Days before a pending offer is flagged to admin for manual follow-up.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='wishlist_default_expiry_days',
            field=models.PositiveIntegerField(default=90, help_text='Default number of days before a wishlist item expires. Users set short/long term per item.'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='condition_acceptable',
            field=models.CharField(choices=[('excellent', 'Excellent or better'), ('good', 'Good or better'), ('fair', 'Fair or better'), ('any', 'Any condition')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='notification_frequency',
            field=models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily digest'), ('weekly', 'Weekly digest')], default='instant', max_length=10),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='size_preference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='term_type',
            field=models.CharField(choices=[('short_term', 'Short-term (urgent or time-limited)'), ('long_term', 'Long-term (ongoing want)')], default='long_term', max_length=20),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='want_type',
            field=models.CharField(choices=[('acquire', 'Looking to acquire permanently'), ('rent', 'Looking to rent temporarily'), ('either', 'Open to either')], default='acquire', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('phones_tablets', 'Phones & Tablets'), ('computers', 'Computers & Laptops'), ('electronics', 'Electronics'), ('gaming', 'Gaming'), ('vehicles', 'Vehicles'), ('fashion', 'Fashion'), ('home_furniture', 'Home & Furniture'), ('health_beauty', 'Health & Beauty'), ('sports_hobbies', 'Sports & Hobbies'), ('tools_equipment', 'Tools & Equipment'), ('handmade_crafts', 'Handmade & Crafts'), ('art_creative', 'Art & Creative'), ('food_plants', 'Food, Plants & Nature'), ('services', 'Services & Commissions'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent — like new'), ('good', 'Good — fully functional, minor wear'), ('fair', 'Fair — fully functional, visible wear'), ('for_parts', 'For Parts / Damaged — not fully functional')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('active', 'Active'), ('paused', 'Paused'), ('traded', 'Traded'), ('expired', 'Expired'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='pending_review', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('iphones', 'iPhones'), ('samsung', 'Samsung'), ('tecno_itel', 'Tecno / Itel'), ('other_android', 'Other Android'), ('tablets', 'Tablets'), ('phone_accessories', 'Accessories'), ('laptops', 'Laptops'), ('desktops', 'Desktops'), ('computer_accessories', 'Accessories'), ('tvs', 'TVs & Displays'), ('audio', 'Audio & Speakers'), ('cameras', 'Cameras & Photography'), ('smart_watches', 'Smart Watches'), ('other_electronics', 'Other Electronics'), ('consoles', 'Consoles'), ('games', 'Games'), ('gaming_accessories', 'Accessories'), ('pc_parts', 'PC Parts & GPUs'), ('cars', 'Cars'), ('motorcycles', 'Motorcycles & Scooters'), ('trucks', 'Trucks & Commercial'), ('mens_fashion', "Men's Fashion"), ('womens_fashion', "Women's Fashion"), ('kids_fashion', "Kids' Fashion"), ('shoes', 'Shoes'), ('bags_accessories', 'Bags & Accessories'), ('sneakers', 'Sneakers'), ('thrift', 'Thrift & Secondhand'), ('furniture', 'Furniture'), ('home_appliances', 'Home Appliances'), ('kitchen', 'Kitchen & Dining'), ('decor', 'Décor & Accessories'), ('health', 'Health & Medical'), ('beauty_skincare', 'Beauty & Skincare'), ('fitness', 'Fitness Equipment'), ('sports', 'Sports Equipment'), ('hobbies_art', 'Hobbies & Art'), ('musical_instruments', 'Musical Instruments'), ('tools', 'Tools & DIY'), ('office_equipment', 'Office Equipment'), ('industrial', 'Industrial & Commercial'), ('crochet_knitting', 'Crochet & Knitting'), ('woodwork', 'Woodwork'), ('resin_art', 'Resin Art'), ('candles_soaps', 'Candles & Soaps'), ('jewellery', 'Jewellery'), ('other_handmade', 'Other Handmade'), ('paintings', 'Paintings & Drawings'), ('sculptures', 'Sculptures'), ('photography', 'Photography'), ('digital_art', 'Digital Art'), ('music', 'Music & Recordings'), ('other_art', 'Other Art'), ('potted_plants', 'Potted Plants'), ('dwarf_trees', 'Dwarf Trees & Bonsai'), ('flowers', 'Flowers'), ('food_produce', 'Food & Produce'), ('seeds_seedlings', 'Seeds & Seedlings'), ('graphic_design', 'Graphic Design'), ('photography_service', 'Photography Service'), ('tailoring', 'Tailoring & Sewing'), ('repairs', 'Repairs & Maintenance'), ('tutoring', 'Tutoring & Training'), ('creative_commission', 'Creative Commission'), ('other_service', 'Other Service'), ('other_items', 'Other Items')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('wishlist_match', 'Wishlist Match'), ('offer_received', 'Offer Received'), ('offer_accepted', 'Offer Accepted'), ('offer_rejected', 'Offer Rejected'), ('offer_countered', 'Offer Countered'), ('offer_timeout', 'Offer Timeout — Admin Alert'), ('seller_demand', 'Seller Demand'), ('trade_opportunity', 'Trade Opportunity'), ('wishlist_expiring', 'Wishlist Item Expiring'), ('listing_expiring', 'Listing Expiring'), ('listing_stale', 'Listing Stale — No Matches'), ('ai_section_updated', 'AI Section Updated by Admin'), ('student_verified', 'Student Email Verified'), ('trade_completed', 'Trade Completed'), ('rating_received', 'Rating Received')], max_length=30),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('countered', 'Countered'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='category',
            field=models.CharField(blank=True, choices=[('phones_tablets', 'Phones & Tablets'), ('computers', 'Computers & Laptops'), ('electronics', 'Electronics'), ('gaming', 'Gaming'), ('vehicles', 'Vehicles'), ('fashion', 'Fashion'), ('home_furniture', 'Home & Furniture'), ('health_beauty', 'Health & Beauty'), ('sports_hobbies', 'Sports & Hobbies'), ('tools_equipment', 'Tools & Equipment'), ('handmade_crafts', 'Handmade & Crafts'), ('art_creative', 'Art & Creative'), ('food_plants', 'Food, Plants & Nature'), ('services', 'Services & Commissions'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='savedlisting',
            unique_together={('user', 'listing')},
        ),
        migrations.AddField(
            model_name='campusmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.campusgroup'),
        ),
        migrations.AddField(
            model_name='campusmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_memberships', to='core.barteruser'),
        ),
        migrations.AddField(
            model_name='listingphoto',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.listing'),
        ),
        migrations.AddField(
            model_name='traderating',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.offer'),
        ),
        migrations.AddField(
            model_name='traderating',
            name='rated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='core.barteruser'),
        ),
        migrations.AddField(
            model_name='traderating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='core.barteruser'),
        ),
        migrations.AddField(
            model_name='campusgroup',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_groups', to='core.universitydomain'),
        ),
        migrations.AlterUniqueTogether(
            name='campusmembership',
            unique_together={('user', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='traderating',
            unique_together={('rater', 'offer')},
        ),
    ]
