# Generated by Django 6.0.5 on 2026-05-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_campusgroup_campusmembership_listingphoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barteruser',
            name='contact_reveal_preference',
            field=models.CharField(choices=[('on_any_offer', 'Reveal to anyone who sends an offer'), ('on_accepted_offer', 'Reveal only after I accept an offer')], default='on_any_offer', max_length=20),
        ),
    ]
