# Generated by Django 6.0.5 on 2026-05-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_backfill_listing_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='suggested_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='suggested_subcategory',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
