# Generated by Django 6.0.5 on 2026-05-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_drop_category_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('phones_tablets', 'Phones & Tablets'), ('computers', 'Computers & Laptops'), ('electronics', 'Electronics'), ('gaming', 'Gaming'), ('vehicles', 'Vehicles'), ('fashion', 'Fashion'), ('home_furniture', 'Home & Furniture'), ('health_beauty', 'Health & Beauty'), ('sports_hobbies', 'Sports & Hobbies'), ('tools_equipment', 'Tools & Equipment'), ('handmade_crafts', 'Handmade & Crafts'), ('art_creative', 'Art & Creative'), ('food_plants', 'Food, Plants & Nature'), ('services', 'Services & Commissions'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='category',
            field=models.CharField(blank=True, choices=[('phones_tablets', 'Phones & Tablets'), ('computers', 'Computers & Laptops'), ('electronics', 'Electronics'), ('gaming', 'Gaming'), ('vehicles', 'Vehicles'), ('fashion', 'Fashion'), ('home_furniture', 'Home & Furniture'), ('health_beauty', 'Health & Beauty'), ('sports_hobbies', 'Sports & Hobbies'), ('tools_equipment', 'Tools & Equipment'), ('handmade_crafts', 'Handmade & Crafts'), ('art_creative', 'Art & Creative'), ('food_plants', 'Food, Plants & Nature'), ('services', 'Services & Commissions'), ('other', 'Other')], max_length=50),
        ),
    ]
