# Generated by Django 6.0.5 on 2026-05-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_restore_category_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
