# Generated by Django 6.0.5 on 2026-05-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_hardcoded_category_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='cash_topup_direction',
            field=models.CharField(choices=[('neither', 'No cash top-up'), ('open', 'Willing to pay or receive a top-up')], default='neither', max_length=20),
        ),
    ]
