# Generated by Django 6.0.5 on 2026-05-17 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_listing_cash_topup_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam or duplicate'), ('prohibited', 'Prohibited item'), ('misleading', 'Misleading or fake'), ('offensive', 'Offensive content'), ('scam', 'Suspected scam'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.listing')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_listings', to='core.barteruser')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('listing', 'reporter')},
            },
        ),
    ]
